# Generated by Django 3.1.7 on 2021-02-27 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=200)),
                ('part', models.CharField(max_length=255)),
                ('partnum', models.CharField(max_length=255)),
                ('partid', models.IntegerField()),
                ('status', models.CharField(max_length=200)),
                ('changed_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
