# Generated by Django 3.1.7 on 2021-02-27 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('USED', 'Used'), ('SENT', 'Sent')], default='NEW', max_length=200),
        ),
        migrations.AlterField(
            model_name='part',
            name='type',
            field=models.CharField(choices=[('MB', 'MB'), ('FHD', 'FHD'), ('KYBD', 'KYBD'), ('ELSE', 'ELSE')], max_length=200),
        ),
    ]
