# Generated by Django 3.1.7 on 2021-03-01 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20210301_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='type',
            field=models.CharField(choices=[('MB', 'MB'), ('FHD', 'FHD'), ('KYBD', 'KYBD'), ('SSD', 'SSD'), ('ELSE', 'ELSE')], max_length=200),
        ),
    ]
